CrystalTettey/Controllers/CrystalManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrystalTettey.Controllers
{
    public class CrystalManagerController : Controller
    {
        //
        // GET: /CrystalManager/

        public ActionResult Index()
        {
            return View();
        }

        
    }
}

CrystalTettey/Controllers/CrystalManagerRelatedLinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CTBusinessLayer;
using CrystalTettey.Models;
using PagedList;
using PagedList.Mvc;

namespace CrystalTettey.Controllers
{

    
    public class CrystalManagerRelatedLinksController : Controller
    {
        CrystalTetteyEntities db = new CrystalTetteyEntities();
        CTBusinessLayer.BusinessLayer dbset = new CTBusinessLayer.BusinessLayer();
        //
        // GET: /CrystalManagerRelatedLinks/

        public ActionResult Index(int? page)
        {
            var ct = dbset.RelatedLinked;
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(ct.ToPagedList(pageNumber, pageSize));
        }

        //
        
        //
        // GET: /CrystalManagerRelatedLinks/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CrystalManagerRelatedLinks/Create

        [HttpPost]
        public ActionResult Create(CTBusinessLayer.RelatedLinks collection)
        {
            if (ModelState.IsValid)
            {
                dbset.AddRelatedLinksDetailsToDB(collection);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /CrystalManagerRelatedLinks/Edit/5

        public ActionResult Edit(int id)
        {
            CTBusinessLayer.RelatedLinks ctitem = dbset.RelatedLinked.Single(emp => emp.linkId == id);
            if (ctitem == null)
            {
                return HttpNotFound();
            }

            return View(ctitem);
        }

        //
        // POST: /CrystalManagerRelatedLinks/Edit/5

        [HttpPost]
        public ActionResult Edit(CTBusinessLayer.RelatedLinks collection)
        {
            if (ModelState.IsValid)
            {
                var num = collection.linkId;
                dbset.SaveChangesRelatedLinksDetailsToDB(collection);
                return RedirectToAction("Index");
            }

            return View(collection);
        }

        //
        // GET: /CrystalManagerRelatedLinks/Delete/5

        [HttpPost]
        public ActionResult Delete(decimal id)
        {
            dbset.DeleteRelatedLinksFromDB(id);
            return RedirectToAction("Index");

            //return View();
        }
    }
}

CrystalTettey/Views/CrystalManagerRelatedLinks/Create.cshtml
@model CrystalTettey.Models.RelatedLinks

@{
    ViewBag.Title = "Create Link";
}

<h2><strong>@ViewBag.Title</strong></h2>

<html>


<body>
    <div class="panel panel-default ">
        <div class="panel-body ">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    @*<legend>RelatedLinks</legend>*@

                    <div class="editor-label">
                        Link Name
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkName, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Description
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkDescription, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkDescription, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Web Address
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkAddress, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkAddress, "", new { @class = "text-danger mark" })
                    </div>

                    <p>
                        <input type="submit" value="Create" class=" btn btn-success" />
                    </p>
                </fieldset>
            }
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index", "", "btn btn-danger")
    </div>

</body>
</html>

CrystalTettey/Views/CrystalManagerRelatedLinks/Edit.cshtml
@model CTBusinessLayer.RelatedLinks

@{
    ViewBag.Title = "Edit Link";
}

<h2><strong>@ViewBag.Title</strong></h2>

<html>

<body>
    <div class="panel panel-default ">
        <div class="panel-body ">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>

                    @Html.HiddenFor(model => model.linkId)

                    <div class="editor-label">
                        Link Name
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkName, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Description
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkDescription, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkDescription, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Web Address
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.linkAddress, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.linkAddress, "", new { @class = "text-danger mark" })
                    </div>

                    <p>
                        <input type="submit" value="Save" class=" btn btn-success" />
                    </p>
                </fieldset>
            }
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</body>
</html>

CrystalTettey/Views/CrystalManagerRelatedLinks/Index.cshtml
@*@model IEnumerable<CTBusinessLayer.RelatedLinks>*@


@model PagedList.IPagedList<CTBusinessLayer.RelatedLinks>
@using CrystalTettey.Models;
@using PagedList;
@using PagedList.Mvc;


@helper Truncate(string
input, int length)
{
    if (input.Length <= length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>...</text>
    }
}
@{
    ViewBag.Title = "Related Links";
}

<h2><strong>@ViewBag.Title</strong></h2>

<p>
    <a class="btn btn-success" @Html.ActionLink("Create New Related Link", "Create")</a>
</p>

<table class="table table-striped">
    <tr class="info">
        <th>
            Link Name
        </th>
        <th>
            Description
        </th>
        @*<th>
                Web Address
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "CrystalManagerRelatedLinks", new { id = item.linkId }))
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.linkName)
                </td>
                <td>
                    @*@Truncate(item.linkDescription, 25)*@
                    @Html.DisplayFor(modelItem => item.linkDescription)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.linkAddress)
                    </td>*@
                <td>  </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.linkId }) |
                    <input type="submit" value="Delete" class="btn btn-warning"
                           onclick="return confirm('Are you sure you want to Delete Item = @item.linkName')">
                </td>
            </tr>
        }
    }

</table>

<div class="container col-sm-offset-4">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </ul>
</div>

<div class="col-lg-6 col-lg-offset-2" id="hButton1">
    <a class="btn btn-danger" @Html.ActionLink("Back to Manager Menu", "Index", "CrystalManager")</a>
</div>