CrystalTettey/Controllers/CrystalManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrystalTettey.Controllers
{
    public class CrystalManagerController : Controller
    {
        //
        // GET: /CrystalManager/

        public ActionResult Index()
        {
            return View();
        }

        
    }
}

CrystalTettey/Controllers/CrystalManagerPhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CTBusinessLayer;
using CrystalTettey.Models;
using PagedList;
using PagedList.Mvc;

namespace CrystalTettey.Controllers
{
    
    public class CrystalManagerPhotosController : Controller
    {
        CrystalTetteyEntities db = new CrystalTetteyEntities();
        CTBusinessLayer.BusinessLayer dbset = new CTBusinessLayer.BusinessLayer();

        // GET: /CrystalManagerPhotos/

        public ActionResult Index(int? page)
        {
            var ct = dbset.PhotoGallerys;
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(ct.ToPagedList(pageNumber, pageSize));
           // return View(ct.ToList());
        }

        
        //
        // GET: /CrystalManagerPhotos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CrystalManagerPhotos/Create

        [HttpPost]
        public ActionResult Create(CTBusinessLayer.PhotoGallery collection)
        {
            if (ModelState.IsValid)
            {
                dbset.AddPhotoDetailsToDB(collection);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /CrystalManagerPhotos/Edit/5

        public ActionResult Edit(int id)
        {
            CTBusinessLayer.PhotoGallery ctitem = dbset.PhotoGallerys.Single(emp => emp.photoId == id);
            if (ctitem == null)
            {
                return HttpNotFound();
            }

            return View(ctitem);
        }

        //
        // POST: /CrystalManagerPhotos/Edit/5

        [HttpPost]
        public ActionResult Edit(CTBusinessLayer.PhotoGallery collection)
        {
            if (ModelState.IsValid)
            {
                var num = collection.photoId;
                dbset.SaveChangesPhotoDetailsToDB(collection);
                return RedirectToAction("Index");
            }

            return View(collection);
        }

        //
        // GET: /CrystalManagerPhotos/Delete/5
                [HttpPost]

        public ActionResult Delete(int id)
        {
            dbset.DeletePhotosFromDB(id);
            return RedirectToAction("Index");
        }

        //
        // POST: /CrystalManagerPhotos/Delete/5

        
    }
}

CrystalTettey/Views/CrystalManagerPhotos/Create.cshtml
@model CrystalTettey.Models.PhotoGallery

@{
    ViewBag.Title = "Create Photo";
}

<h2><strong>@ViewBag.Title</strong></h2>

<html>

<body>
    <div class="panel panel-default ">
        <div class="panel-body ">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    @*<legend>PhotoGallery</legend>*@

                    <div class="editor-label">
                        Photo Name
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.photoName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.photoName, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Description
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.photoDescription, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.photoDescription, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Alternate Name
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.photoAltName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.photoAltName, "", new { @class = "text-danger mark" })
                    </div>

                    <div class="editor-label">
                        Photo Link Address
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.photoLink, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        @Html.ValidationMessageFor(model => model.photoLink, "", new { @class = "text-danger mark" })
                    </div>

                    <p>
                        <input type="submit" value="Create" class=" btn btn-success" />
                    </p>
                </fieldset>
            }
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index", "", "btn btn-danger")
    </div>
</body>
    </html>

   

CrystalTettey/Views/CrystalManagerPhotos/Edit.cshtml
@model CTBusinessLayer.PhotoGallery

@{
    ViewBag.Title = "Edit Photo";
}

<h2><strong>@ViewBag.Title</strong></h2>

<html>

<body>
    <div class="panel panel-default ">
        <div class="panel-body ">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)


                @*<legend>PhotoGallery</legend>*@

                @Html.HiddenFor(model => model.photoId)

                <div class="editor-label">
                    Photo Name
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.photoName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                    @Html.ValidationMessageFor(model => model.photoName, "", new { @class = "text-danger mark" })
                </div>

                <div class="editor-label">
                    Description
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.photoDescription, new { htmlAttributes = new { @class = "form-control input-lg" } })
                    @Html.ValidationMessageFor(model => model.photoDescription, "", new { @class = "text-danger mark" })
                </div>

                <div class="editor-label">
                    Alternative Name
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.photoAltName, new { htmlAttributes = new { @class = "form-control input-lg" } })
                    @Html.ValidationMessageFor(model => model.photoAltName, "", new { @class = "text-danger mark" })
                </div>

                <div class="editor-label">
                    Photo Link Address
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.photoLink, new { htmlAttributes = new { @class = "form-control input-lg" } })
                    @Html.ValidationMessageFor(model => model.photoLink, "", new { @class = "text-danger mark" })
                </div>

                <p>
                    <input type="submit" value="Save" class=" btn btn-success" />
                </p>


            }
        </div>
    </div>
            <div>
                @Html.ActionLink("Back to List", "Index", "", "btn btn-danger")
            </div>

</body>
</html>

CrystalTettey/Views/CrystalManagerPhotos/Index.cshtml
@*@model IEnumerable<CTBusinessLayer.PhotoGallery>*@
@model PagedList.IPagedList<CTBusinessLayer.PhotoGallery>
@using CrystalTettey.Models;
@using PagedList;
@using PagedList.Mvc;


@helper Truncate(string
input, int length)
{
    if (input.Length <= length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>...</text>
    }
}

@{
    ViewBag.Title = "Photo Gallery";
}

<h2><strong>@ViewBag.Title</strong></h2>

<p>
    <a class="btn btn-success" @Html.ActionLink("Add New Photo", "Create")</a>
</p>
<table class=" table table-striped">
    <tr class="info">
        <th>
           Photo Name
        </th>
        <th>
            Description
        </th>
        <th>
            Alt Photo Name
        </th>
        @*<th>
            Photo Link
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    using (Html.BeginForm("Delete", "CrystalManagerPhotos", new { id = item.photoId }))
        {
         
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.photoName)
        </td>
        <td>
            @Truncate(item.photoDescription, 35)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.photoAltName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.photoLink)
        </td>*@
        
            <td>  </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.photoId }) |
            <input type="submit" value="Delete" class="btn btn-warning"
                   onclick="return confirm('Are you sure you want to Delete Item = @item.photoName')">
        </td>

    </tr>
}
}
</table>

<div class="container col-sm-offset-4">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </ul>
</div>

<div class="col-lg-6 col-lg-offset-2" id="hButton1">
    <a class="btn btn-danger" @Html.ActionLink("Back to Manager Menu", "Index", "CrystalManager")</a>
</div>